### ISSUE TITLE
Implementing Snape's AVO model and multi-model

### ISSUE THREAD

**Issue by pgruenbacher** [MengeCrowdSim/Menge#103]
I saw Snape's AVO library http://gamma.cs.unc.edu/AVO/. I'm guessing I can just see how you adopted the RVO2 github library into the orca model within Menge and use that as a reference for implementing AVO as a model. Snape seems to be in the same research group so I'm not sure why you guys aren't just adopting all of your new models into the Menge framework ;). I definitely appreciate a research group that actually publishes their code though along with their papers, so I really appreciate what you've done so far.

I'm using the Menge simulator for modeling thousands of units in an RTS-like game. I'd like to use the ORCA model for infantry whereas I'd like to use the AVO model for cavalry that have certain acceleration and steering limitations. Before I go down the rabbit hole, does it seem feasible to have two different models being applied to two different groups of agents (infantry and cavalry)?

**Comment by MengeCrowdSim** [comment]
First, thanks! Always nice to be appreciated.

There are a few *VO pieces of code that don't reside in Menge. There is a certain beautiful symmetry in bringing them together. Your descent down the rabbit hole would definitely help.  :)  That said, in the current state of things, the hole won't go very deep and you *will* run into some concrete (so don't dive head first).

__Short answer__: currently Menge is architected to only work with agents which all share the same local planner (all ORCA, all Helbing, etc.) It actively confounds the idea of mixing. There are a couple of reasons for this:
  1. At the time, we wanted to limit virtual calls at the per-agent level.
  2. What if one agent model requires a parameter of the *other* agent that isn't defined in the other agent's model?  Where will that value come from?

__Long answer__: It is our intent to modify the design to allow mixing agent models. It's on the radar, but it isn't scheduled in any sense of the word. More a desire than a goal.

There's a way around this. You can create a *new* agent that, essentially, is a union of other agents. The ham-fisted solution would be to make a `MetaAgent` that directly contains an `ORCA` and `an AVO` agent and uses internal logic to decide which one is active. (And also allows you to make whatever decisions you need to make in getting an AVO agent to interact with an ORCA agent). For any given agent, one of those two agents would be null and the other would be fully populated. However, you still have to sub-class `BaseAgent` which *will* lead to redundant fields (radius stored both in the `MetaAgent` and the contained `ORCA` agent).

An alternative approach would be to sub-class the OrcaBaseAgent (or the OrcaAgent) into the `MetaAgent`, merely adding the AVO components to that with a switch defining which set of code to use. This works because you only want to mix *two* types of agents.

Sorry for the hacky alternatives, but until we push everything into a completely generic Agent interface to support heterogeneous models, there aren't a lot of alternatives.

**Comment by MengeCrowdSim** [comment]
FTR I'm assuming you've already tried modeling the horses with ORCA and lower maximum acceleration values? It's not the same as *planning* w.r.t. acceleration, but it gives you agents that can't take sharp corners or stop on a dime.

**Comment by pgruenbacher** [comment]
I had considered but hadn't tested. That's probably the better fit for me anyway. Horses have high max vel but low accel. Infantry have high accel but low max vel. I can also probably just do a plugin agent that has sume custom velocity logic to limit steering acceleration at high speeds vs low speeds.

**Comment by MengeCrowdSim** [comment]
The way the acceleration limits use are also pretty simplistic. The fact that accelerations are limited isotropically is ridiculous (certainly, a horse can accelerate much faster in the forward direction than any other direction). Also, it makes sense to have some kind of state-based limit. For example, in an emergency, an agent could exert *extra* effort to stop (increasing the acceleration limit). Encoding the "emergency" state would help. And even in the general case, humans tend to apply higher acceleration to *stopping* than to *starting* (stopping being more important to avoid walking into things.)  So, there's a lot to be desired in the acceleration limits code. Someday, I may factor that out into its own element to allow mix-and-match acceleration constraints.

**Comment by pgruenbacher** [comment]
@MengeCrowdSim 
some more questions as I try to implement the code into a more dynamic environment.

Let's say I'm wanting to have two different groups of agents. The agents in group 1 have their own formation and the other group has its own formation as well. It doesn't make sense to make two different states for each formation, since agents in both group are in the "formation" state, just pointing to two different formations. So either 

- a) I make a FSM instance that handles each group of agents seperately with different state instances but similar conditions, events, etc. However I'm worried that reduces performance linearly with each new FSM instance since the parallelism is in the `doStep`. 

- b) I make a "DynamicFormationVelModifier" which would have a formationModiifer instance for each group of agent. I'll be trying this first.

I likewise need to implement similar logic for goals, and also making the goals being dynamically set. Basically I need to implement logic where a group of agents of class="1" will have different state/goals instances compare to a group of agents of class="2", while still having the same FSM logic graph. 

Finally I need to implement an "enemy" attraction/repulsion velocity modifier state which should be pretty straightforward. Likewise waypoints implementation should be straightforward.

**Comment by MengeCrowdSim** [comment]
It isn't clear to me what problem you're solving.  Here's what I infer:

You've got two different "groups" of agents. They are basically identical in behavior (so they'd have the same FSM) *except* for their formation.  However, in their overall BFSM, only one state dictates that they move in formation and, therefore, you'll have the formation velocity modifier applied to that single state. You're encoding groups by using the class id so, on a per-agent basis, there is a way to tell which agent belongs in which group.

Now, assuming that I've accurately restated the situation you're looking at, I'd offer up the following thoughts:

1. There's nothing wrong with having two different states for two different formations. The cost of the two states is negligible.
2. It seems the real issue is that you have two different classes of agents walking through the same BFSM, but when they move to formation, they need to move to *different* formation states. You might create a custom "TransitionTarget" that selects the target of the transition based on the class id. Then when it's time to transition to formation, you transition to a "dummy" state that has an *auto*-conditioned transition out with a class-based target that would send agents to different target states based on their class. This might be the simplest way to achieve what you're looking for.

You could do the same thing with the goal selector -- a class-based goal selector.

Again, all of this assumes that you're looking to minimize the number of states in the FSM. You shouldn't worry about the performance based on the size of the overall FSM. It really doesn't have any bearing there. A Menge BFSM can actually be defined of a bunch of disconnected BFSMs so that some agents work through one connected graph, and other agents work through a different connected graph, but agents can never cross. That's the simplest way to achieve your end goal (without writing new code). The *only* downside is that if you want the *structures* of the two BFSM to be the same (but some of the details to be different), you'll have to make sure you keep them synchronized.

**Comment by pgruenbacher** [comment]
Yes actually ha I actually came to the same solution. I wasn't worried about states, I just didn't want to redefine transitions for each group of agents.

I've started making a Target Transition class that will accept a state type as a parameter. Then it looks for states that match the typename and the agent class. E.g. for two agent groups of class 1 and 2...

<State name="ex1" type="example" class="1">
<State name="ex2" type="example class="2">
<Transition>
    <Target type="select_by_class" typename="example"/>
</Transition>

This does mean that I added the type and class parameters to the State class.

For your bunch of disconnected BFSMs mention... I didn't see any indication of that in the code. What would that look like in the xml.

**Comment by pgruenbacher** [comment]
![ezgif-2-507938a3ea](https://user-images.githubusercontent.com/3332598/43051072-6bd5a588-8de1-11e8-9937-93b831e57490.gif)
got it working.

**Comment by MengeCrowdSim** [comment]
Niiiice. Glad it worked out for you. Here are some further thoughts that popped into my head while I considered your solution.

I wouldn't have added "type" and "class" to State. I would've provided the mappings directly in the transition:

```xml
<Transition from="">
  <Target type="select_by_class">
    <ClassMap class="1">
      <.../>
    </ClassMap>
    <ClassMap class="2">
      <.../>
    </ClassMap>
  </Target>
</Transition>
```

And in that `<.../>` I would've opened up to arbitrary target types -- so it can be a single target, or random selection from a set, or even a return target. Generally, I prefer to minimize modifications to a class if that class doesn't actually use the data. As it is, every state is named, so you can reference them perfectly well.

Based on this discussion, I may do that anyways.  :) This kind of functionality has definite utility. If you'd like to, you can submit a PR. Always nice to give back.  :D

Also, another possibility would have been to create a target condition that keyed on agent class. Then the overall transition condition would have been an "AND" condition (ie., "original condition" AND "class = whatever".

The thing about Menge, is that there's usually a dozen ways to solve the same problem.

**Comment by pgruenbacher** [comment]
Yea. I did it my way cause I wanted to make it clear in my transitions that agents of class 1 and class 2 have the *exact* same transition flow, but with just pointing to different state instances of the same type. 

I'm also implementing a FormationsVelocityComponent class that is essentially the same as the formationVelocityModifier class. The point being that the formation points themselves are the goals in my case. As the game progresses the position and rotation of the formation will dynamically change. The issue with the velocity modifier of formations (which can be visible in the formationNavigation example) is that if an agent gets stuck, the agents in the formation will struggle as they try to return back to the overall average position of the agents (it starts to shift backwards after reaching right side). 

Take a look at godot game engine by the way as an alternative to Unity support. If i do a PR it'll be a Menge fork or module that will tie-in to godot as an api. Open-source gotta support open-source.
