### ISSUE TITLE
Path Modification 

### ISSUE THREAD

**Issue by dkal3** [MengeCrowdSim/Menge#133]
Hi!!
I deal with PedVO Algorithm and run example 4square. 
I would be grateful if you could clarify to me some things.
How I can modify the path that agents follow. Specifically,  when agents are very close to obstacles their speed is decreasing. Am I right? When this is happening I would like to change their position-path for a bit and continue from the new position.
From PedVOAgent.cpp and function obstacleLine() I made some attempts with no result.
Thank you in advance!!!

**Comment by curds01** [comment]
Sorry for the delayed response. I'd meant to answer this immediately and then got distracted. You know how that goes.

The key to understanding Menge is to keep two concepts separate in your mind: global path planning and local collision avoidance.

- global path planning is, as the name suggests, the "path" the agent *wants* to take to reach its goal. In the simplest of scenarios, the path can be "walk straight to the goal". In complex environments (like the maze example) that *can't* work.
- local collision avoidance is how a path gets exercised. At any given moment the path planner produces an instantaneous *preferred* velocity. The local collision avoidance figures out if this is a *viable* velocity and, if not, adapts it to all of the moving obstacles. This local collision avoidance model *is* the pedestrian model.

In the 4squares example, you have a very weird scenario. The path planner is using a really simple path planner: walk straight to goal. This is not in any way an optimal path because it points into obstacles. However, the obstacles are convex, and the agents can slide along the obstacles and make progress toward their goal (even if it's slower). Generally, in modeling humans, paths that send agents into obstacles are *bad* paths.

So, to really change the observed behaviors in 4squre, you need to change the *velocity component* from a simple "goal" type to one that will either use a roadmap or a navigation mesh to find paths *around* the obstacles.

**Comment by dkal3** [comment]
Yes!! No problem, I understand!!!
Ok thank you from your answer!!!
I will try it!!
