### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chraibi** [MengeCrowdSim/Menge#27]
For the demo videos like for example this [one](http://gamma.cs.unc.edu/Menge/intro_vids.html#crowdmodels)

it would be helpful to have the project files so that people can try it.
(nice to have for lectures)

**Comment by MengeCrowdSim** [comment]
The project files for this (and most of the videos) are included in Menge.

The crowd-model comparison requires a bit extra effort.  If you look in the file: $MengeRoot$/Exe/allExamples you'll see several lines:

./menge -p ../examples/core/pedModelSwap.xml -m orca -t 0.1
./menge -p ../examples/core/pedModelSwap.xml -m helbing -t 0.1 --subSteps 9
./menge -p ../examples/core/pedModelSwap.xml -m karamouzas -t 0.1 --subSteps 9

This references the project that drives the video to which you linked.  It runs it with three different models (via the -m flag).  In order for this to work, you'll need to build the plugins because the helbing and karamouzas models are part of the plug ins.
