### ISSUE TITLE
Simulation does not finish (except for maximum time limit).

### ISSUE THREAD

**Issue by HendrikBV** [MengeCrowdSim/Menge#84]
I'm trying to model groups of people traveling from one room in the building to another room in the building (more precisely, at a university when switching rooms between consecutive lectures, I want to model the flows of all traveling students). 

I have a goal in each room of the building (a point) and each agent group starts in a state where they want to travel towards that goal. I also have a final "stop" state to indicate when an agent has reached his or her destination. However, to avoid agents blocking the doors of the rooms for other pedestrians I teleport them away to a location further away, see xml excerpt below.

![image](https://user-images.githubusercontent.com/38352715/38735910-937c22ac-3f2a-11e8-984c-b6a7d6e4e93b.png)

![image](https://user-images.githubusercontent.com/38352715/38736803-83b49b3a-3f2d-11e8-9218-b4b8f50c8e21.png)

What I then want to do is record the time it takes for the last agent to reach his or her destination. The simulation time limit is set to 1800 seconds. However, sometimes the simulation does not finish, i.e. some agents never seem to reach their destinations. When this happens, I try the calculations again. The weird thing is that sometimes it does finish and then with e.g. 300 seconds travel time. (Now, I know that the results are stochastic and thus can differ between runs because agent's preferred free walking speed is drawn from a normal distribution.) 

For the PedVO model, I have been able to reproduce the issue with visualization.

![image](https://user-images.githubusercontent.com/38352715/38736103-476a83f8-3f2b-11e8-9fac-7ab12a040aab.png)

Pedestrians seem to block the hallway. Moreover, some pedestrians get stuck behind the wall of the adjacent room. After that, they are stuck and can't seem to find the way back towards their goal? I'm using a road map. I guess they take the nearest node (opposite the wall) instead of the nearest feasible node (inside the room)?

I have tried the other pedestrian models as well and sometimes they seem to work for the same specific problem data, only to fail for other problem data.

I'm wondering whether this issue is because I set the goals, states and transitions wrongly or if this is simply due to the large number of people that travel through relatively narrow hallways? Moreover, is there any solution I can implement to avoid this problem? 

Another problem that I have seen with the social-force models is that after teleportation when the agents are in their final state they are still moving, so that the simulation does not finish. However, they should be in their final state, so I don't understand how this works.

Thanks in advance.

**Comment by curds01** [comment]
As I read your snippet, it should be the case that a final simulation is "empty" (i.e., all agents have been teleported off to some distant, unvisualized space). Correct? And, if so, the problem is that the agents are not successfully navigating to their goals.

So, this could be related to the definition of the goals and could be related to the definition of the roadmap (or some combination of both). The best thing you could do is give me access to the full simulation specification and I can take a look at it.

**Comment by HendrikBV** [comment]
That is correct. Here are the specifications for which the problem occurs.

[behavior.txt](https://github.com/MengeCrowdSim/Menge/files/1907872/behavior.txt)
[scene.txt](https://github.com/MengeCrowdSim/Menge/files/1907873/scene.txt)
[view.txt](https://github.com/MengeCrowdSim/Menge/files/1907874/view.txt)
[Road_Map_KUL.txt](https://github.com/MengeCrowdSim/Menge/files/1907881/Road_Map_KUL.txt)

**Comment by curds01** [comment]
As I look at your data, your problem most likely stems from your definition of obstacles. Menge works best with closed polygons. I note that your obstacles are defined as a concatenation of line segments.  (I.e., a whole bunch of 2-vertex obstacles). Menge's reasoning includes looking around corners. However, when you have two convex obstacles which are different obstacles, but coincident at end points, Menge can't look around corners. It has no knowledge that the two walls are connected. You'll note in the office example that all of the walls have "thickness" ; there are no interior walls that are simply line segments.

Given the complexity of the environment you've created, correcting the obstacle definition might be problematic. At, the very least, it'll be painful to re define each floor to have walls with thickness.  So, I'll ponder what can be done about this.

**Comment by HendrikBV** [comment]
Thank you for your response.

I have changed the definition of the obstacles so that all walls have thickness and that all walls that are connected are defined as a single obstacle. I have attached the new scene specification below.

[scene_new.txt](https://github.com/MengeCrowdSim/Menge/files/1921365/scene_new.txt)

However, the same problem occurs. Here you see that some agents are pushed back into the room and they get stuck behind the obstacle.

![image](https://user-images.githubusercontent.com/38352715/38893219-f1747816-4289-11e8-9950-873d68cd1587.png)

Here the agent wants to reach the vertex of the road map opposite the wall, but does not know that (s)he should go around the corner. 

![image](https://user-images.githubusercontent.com/38352715/38893235-fdcc1f24-4289-11e8-8314-01a0a84801c6.png)

Perhaps my redefinition of obstacles is still wrong?

**Comment by curds01** [comment]
My first test to validate the "waypoint visibility" hypothesis is insufficient.

 I created a small scenario in which an agent is swept up by a larger crowd into a space in which *none* of the path waypoints are visible. The attached image illustrates the scenario as time progresses (and the simulation project is attached below).

Essentially, the key is that the agent remembers the *last* location it was at when it could see waypoints and that becomes its waypoint. This scenario is insufficient, because heading back to that point is actually possible. It seems in your scenario, the last position at which the path points was visible is no longer directly reachable.

So, tomorrow I'll do another variation of this scenario -- one in which the position waypoints were *last* visible is no longer reachable after the agent is finished being swept. But I can easily imagine what is wrong with the code -- if the path isn't visible at all, it only remembers the last location it *could* see the path. In reality, if *that* position isn't visible, it really needs to replan.

![simulation](https://user-images.githubusercontent.com/22562264/38911707-9842243c-42c0-11e8-9d1b-3afe5192db1f.jpg)

[roadmap_hijack.zip](https://github.com/MengeCrowdSim/Menge/files/1922445/roadmap_hijack.zip)

**Comment by HendrikBV** [comment]
For different simulation scenarios in the same building geometry (different agent groups with different goals) the simulation now always finishes successfully.

![image](https://user-images.githubusercontent.com/38352715/38928797-9d61cfe0-430a-11e8-85e5-832af4a0bc67.png)

**Comment by curds01** [comment]
You've essentially captured the fix. There are a couple of small details I'm planning on doing differently (related to memory management, synchronization, and replanning frequency) but that's the basic shape. This evening, I'll PR my fix and ping you on it. Then I'll merge it and you can just update from master.
